"""empty message

Revision ID: 4171607ea991
Revises: f15b6a49c434
Create Date: 2024-07-11 22:32:29.666143

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4171607ea991'
down_revision = 'f15b6a49c434'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('book_club_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['book_club_id'], ['book_clubs.id'], name=op.f('fk_Comments_book_club_id_book_clubs')),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('discussions')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('discussions',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), nullable=False),
    sa.Column('content', sa.TEXT(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('book_club_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['book_club_id'], ['book_clubs.id'], name='fk_discussions_book_club_id_book_clubs'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('Comments')
    # ### end Alembic commands ###
