"""empty message

Revision ID: f1718427e987
Revises: 2ef556aac82e
Create Date: 2024-07-14 22:35:06.736539

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1718427e987'
down_revision = '2ef556aac82e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book_club', schema=None) as batch_op:
        batch_op.add_column(sa.Column('genre', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book_club', schema=None) as batch_op:
        batch_op.drop_column('genre')

    # ### end Alembic commands ###
